version: "3.9"

services:
  db:
    image: postgres:9.6
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  redis:
    image: redis

#  rq:
#    build: .
#    command: python manage.py rqworker default
#    volumes:
#      - .:/code
#    links:
#      - redis
#
#  rqscheduler:
#    build: .
#    command: python manage.py rqscheduler
#    volumes:
#      - .:/code
#    links:
#      - redis

#  rqdashboard:
#    build: .
#    command: rq-dashboard -p 9181 -u 'redis://redis/0'
#    ports:
#      - "9181:9181"
#    volumes:
#      - .:/code
#    links:
#      - redis

  wkhtmltopdf:
    image: openlabs/docker-wkhtmltopdf-aas
    ports:
      - "80:80"
    volumes:
      - .:/code

