version: "3.9"

services:
  db:
    image: postgres:9.6
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - wkhtmltopdf

  redis:
    image: redis

  rq:
    build: .
    command: python manage.py rqworker
    volumes:
      - .:/code

  wkhtmltopdf:
    image: openlabs/docker-wkhtmltopdf-aas
    ports:
      - "80:80"
    volumes:
      - .:/code

