# Generated by Django 3.1.7 on 2021-03-29 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=36, unique=True)),
                ('check_type', models.CharField(choices=[('k', 'kitchen'), ('c', 'client')], max_length=1)),
                ('point_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('k', 'kitchen'), ('c', 'client')], max_length=1)),
                ('order', models.JSONField()),
                ('status', models.CharField(choices=[('n', 'new'), ('r', 'rendered'), ('p', 'printed')], max_length=1)),
                ('pdf_file', models.FileField(null=True, upload_to='pdf/')),
                ('printer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='checkservice.printer')),
            ],
        ),
    ]
